name: sayer_version2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #Enable to override the white screen in app initializtion  
  flutter_native_splash: ^2.4.6  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   #read all images inside the images folder.
   - assets/images/


  #read all fonts
  fonts:
      #font name that will be used in the app
    - family: "Montserrat"
      fonts: 
        - asset: "assets/fonts/Montserrat-Arabic-Regular.ttf"
  
